# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-15 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baskets', '0002_auto_20170914_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(default=0.0, help_text='price in EUR'),
        ),
    ]
