# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-25 20:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baskets', '0003_auto_20170915_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_touched', models.DateTimeField(verbose_name='date last touched')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=127, verbose_name='name of event')),
                ('event_date', models.DateField(verbose_name='date of event')),
                ('description', models.TextField(verbose_name='description of event')),
                ('created', models.DateTimeField(verbose_name='date created')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='currentevent',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baskets.Event'),
        ),
        migrations.AddField(
            model_name='basket',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='baskets.Event'),
        ),
        migrations.AddField(
            model_name='item',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='baskets.Event'),
        ),
    ]
